[package]
name = "rust-pip"
version = "0.0.1"
edition = "2021"
description = "WORK IN PROGRESS: Pip rewritten in Rust"
authors = ["Jan Bronicki janbronicki@gmail.com"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/John15321/rust-pip"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
anyhow = { version = "1.0.58", features = ["backtrace"] }
reqwest = { version = "0.11", features = ["blocking", "json", "stream"] }
structopt = { version = "0.3.26", features = ["color"] }
strum = "0.24.1"
strum_macros = "0.24.2"
indicatif = "0.17.0"
lazy_static = "1.4.0"
serde = {version = "1.0.143", features = ["derive"]}
pomsky-macro = "0.5.0" # 0.6.0 doesnt work for me ;-;

[dev-dependencies]
