name: 🔨 Build

on:
    pull_request:
    push:
        branches: ["main", "develop", "release"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
        name: 🔨 Build release
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Build release
              run: cargo build --release

    package:
        name: 📦 Check package generation
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Check package generation
              run: cargo package

