name: Docs

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    docs:
        name: 📄Build docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: 📄Build docs
              run: cargo doc --verbose
