name: 👔 Check formatting

on:
    pull_request:
    push:
        branches: ["main", "develop", "release"]

env:
    CARGO_TERM_COLOR: always

jobs:
    check_format:
        name: 👔 Check formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Check Formatting
              run: cargo fmt -- --verbose --check --color auto

