
name: 🖋  Check lintig

on:
    pull_request:
    push:
        branches: ["main", "develop", "release"]

env:
    CARGO_TERM_COLOR: always

jobs:
    check_lint:
        name: 🖋 Check linting
        runs-on: ubuntu-latest
        steps:
            - name: Check linting
              run: |
                  rustup component add clippy
                  set env RUSTFLAGS="-Dwarnings"
                  cargo clippy --workspace -- -D warnings

