name: 🧪 Tests

on:
    pull_request:
    push:
        branches: ["main", "develop", "release"]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
        name: 🔨 Build release
        runs-on: ${{ matrix.os }}
        name: 🧪 Run tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run tests
              run: cargo test --verbose
